from promptflow import tool

@tool
def synthesize_analysis(case_study: str, requirements: str, architecture: str) -> str:
    """Synthesize all analysis results into final report"""
    
    report = f"""# Architecture Solution Analysis

## Case Study
{case_study}

## Requirements Analysis
{requirements}

## Architecture Design
{architecture}

## Summary
This analysis provides a comprehensive Azure solution for the given case study.

---
*Generated by Azure AI Foundry Interview Assistant*
"""
    
    return report
